import { PROJECTS, PROJECT_TYPES, DATA_SOURCES } from './data/projects.js';

const TILE_SIZE = 256;
const MIN_ZOOM = 6;
const MAX_ZOOM = 15;
const DEFAULT_VIEW = { lat: 23.78, lng: 120.98, zoom: 7 };
const LANG_KEY = 'taiwan-construction-map-language';

const COPY = {
  zh: {
    documentTitle: '台灣工程地圖｜Taiwan Construction Map', skipLink: '跳到工程資訊', brandEyebrow: '工程位置 × 進度 × 甲乙方', brandTitle: '台灣工程地圖', brandSubtitle: 'Taiwan Construction Map', navMap: '工程地圖', navSources: '資料入口', navGuide: '補資料',
    heroPill: '預設 OpenStreetMap，並可切換官方電子圖、灰階、航照與地籍參考套疊。', heroTitle: '台灣正在升級的地方，一張圖先 get。', heroText: '給工程公司、發包甲方、地圖控與年輕使用者看的工程雷達。先看位置與施工範圍，再看甲方、乙方、開工日、預計完工與啟用日；資訊不迷路，城市進度直接開圖。',
    metricProjects: '工程/資料圖層', metricCost: '工程級距總覽', metricSources: '可查資料入口', panelEyebrow: '工程雷達', panelTitle: '先找地點，再看工程脈絡', panelText: '輸入地名、工程名、廠商或發包單位，快速定位。適合估案、查進度、看城市變化，也適合地圖玩家開圖探索。',
    searchLabel: '搜尋', searchPlaceholder: '例：淡江大橋、高雄捷運、工信工程、道路挖掘', typeLabel: '類型', typeAll: '全部類型', statusLabel: '狀態', statusAll: '全部狀態', resetMap: '回到全台', toggleSources: '看資料入口',
    legendPublic: '公共工程', legendTransit: '捷運/交通', legendRoad: '道路/管線', legendPlanning: '規劃/環評', legendBuilding: '建築/園區', mapEyebrow: '互動底圖＋工程圖層', mapTitle: '台灣工程現場一眼看', mapNote: '可拖曳、縮放、查看道路地名與城市位置。手機瀏覽時先順滑看內容，需要移動地圖時再點一下啟用。', mapLoading: '電子地圖準備中，工程清單仍可先查。',
    sourcesEyebrow: '資料入口', sourcesTitle: '工程資料很分散，要分層查才準。', sourcesText: '公共工程、採購決標、重大建設、道路挖掘、環評、建管、能源水利與地方開放資料各有入口。這裡把常用平台集中，方便工程公司、甲方、地圖控交叉查證。',
    guideEyebrow: '補資料指南', guideTitle: '資料要好用，關鍵是位置、來源與欄位一致。', guide1Title: '1. 補上工程基本盤', guide1Text: '工程名、地點、甲方、乙方、經費、開工日、預計完工日與啟用日要盡量完整，查案才順。', guide2Title: '2. 標清楚施工範圍', guide2Text: '橋梁、道路、捷運適合畫路線；園區與基地適合畫範圍；單一設施用標記點。地圖準，信任感就上來。', guide3Title: '3. 來源要能回查', guide3Text: '每筆資料都盡量附官方公告、採購資料、工程頁面或地方圖台。看到來源，資訊力直接 up。', guide4Title: '4. 手機先好用', guide4Text: '現場人員、通勤族、地圖控多半用手機看；清單、篩選、地圖點擊都要單手可用、載入快速。',
    footerTitle: '台灣工程地圖｜Taiwan Construction Map', footerText: '工程位置、經費、期程與甲乙方資料，請以各主管機關、政府電子採購網、公共工程雲端服務網、建管、環評與地方圖台最新公告為準。地圖底圖與官方圖資來源，請以地圖上的即時來源註記為準。',
    emptyTitle: '沒有符合條件的工程', emptyText: '換個地名、工程名、甲方或乙方，讓地圖重新開圖。', owner: '甲方', contractor: '乙方', cost: '經費/級距', area: '施工範圍', ownerFull: '發包甲方', contractorFull: '乙方/廠商', startDate: '開工日期', expectedFinish: '預計完工日', expectedOpen: '預計啟用日', source: '資料來源', missing: '待官方資料回填', openSource: '打開資料來源 ↗', openMap: '用 OpenStreetMap 看位置 ↗', sourceFit: '適合查：', sourceCta: '前往資料入口', metricCostValue: '多層級', mapReady: '互動工程地圖已載入，可拖曳縮放、切換底圖並點選工程熱點。', initHint: '可拖曳、滾輪縮放，點選工程熱點看甲方、乙方、工期與來源。需要官方電子圖、航照或地籍參考時可切換底圖。', resetHint: '已回到全台視角，點選任一工程熱點開始探索。', filterEmpty: '目前沒有符合條件的工程，換個地名、廠商或資料入口再試試。', mapTouchEnable: '啟用地圖', mapTouchDisable: '鎖住地圖', mapTouchActive: '地圖拖曳已開啟；再點一次可恢復網頁滑動優先。', mapTouchLocked: '手機滑動已改成網頁優先，不會被地圖卡住。要移動地圖請點「啟用地圖」。', languageButton: 'EN', ariaLanguage: 'Switch to English', zoomControl: '地圖縮放', zoomIn: '放大地圖', zoomOut: '縮小地圖'
  },
  en: {
    documentTitle: 'Taiwan Construction Map｜Engineering Radar', skipLink: 'Skip to engineering info', brandEyebrow: 'Location × Progress × Owner / Contractor', brandTitle: 'Taiwan Construction Map', brandSubtitle: 'Engineering Radar', navMap: 'Map', navSources: 'Sources', navGuide: 'Data guide',
    heroPill: 'OpenStreetMap by default, with official street map, light map, aerial imagery, and cadastre reference overlay options.', heroTitle: 'Taiwan’s upgrades, mapped in one view.', heroText: 'A construction radar for engineering firms, project owners, map lovers, and younger readers. Check location, work area, owner, contractor, start date, target finish, and opening timeline without getting lost in scattered sources.',
    metricProjects: 'Projects / layers', metricCost: 'Cost levels', metricSources: 'Source portals', panelEyebrow: 'Engineering radar', panelTitle: 'Find a place, then read the project story', panelText: 'Search by place, project name, contractor, or owner. Useful for bid scouting, progress checks, city watching, and map exploration.',
    searchLabel: 'Search', searchPlaceholder: 'Example: Tamkang Bridge, Kaohsiung MRT, road works', typeLabel: 'Type', typeAll: 'All types', statusLabel: 'Status', statusAll: 'All status', resetMap: 'Taiwan view', toggleSources: 'Source list',
    legendPublic: 'Public works', legendTransit: 'Transit / traffic', legendRoad: 'Road / utilities', legendPlanning: 'Planning / EIA', legendBuilding: 'Buildings / parks', mapEyebrow: 'Interactive base maps + project layers', mapTitle: 'Construction sites at a glance', mapNote: 'Drag, zoom, and read city locations. On mobile, page scrolling comes first; tap once when you want to move the map.', mapLoading: 'Map is loading. The project list is still ready.',
    sourcesEyebrow: 'Source portals', sourcesTitle: 'Engineering data is scattered. Layered checking is the smart move.', sourcesText: 'Public works, procurement awards, major projects, road works, EIA, building permits, energy, water, and local open data all live in different places. This page gathers common entry points for cross-checking.',
    guideEyebrow: 'Data guide', guideTitle: 'Good data needs clear location, source, and fields.', guide1Title: '1. Add the core project facts', guide1Text: 'Project name, location, owner, contractor, budget, start date, target finish, and opening date make case tracking much smoother.', guide2Title: '2. Mark the work area clearly', guide2Text: 'Bridges, roads, and rail lines work well as routes; parks and campuses need area shapes; single facilities can use pins. Accurate maps build trust.', guide3Title: '3. Keep sources traceable', guide3Text: 'Attach official notices, procurement records, project pages, or local map portals whenever possible. Source clarity is instant credibility.', guide4Title: '4. Mobile-first for real users', guide4Text: 'Site staff, commuters, and map fans often check by phone. Lists, filters, and map taps should be easy with one hand and quick to load.',
    footerTitle: 'Taiwan Construction Map', footerText: 'For project location, budget, timeline, owner, and contractor data, please verify with the latest official notices from competent authorities, procurement portals, public works systems, building management, EIA records, and local map portals. For base maps and official geospatial layers, follow the live source note shown on the map.',
    emptyTitle: 'No matching projects', emptyText: 'Try another place, project name, owner, or contractor to reopen the map view.', owner: 'Owner', contractor: 'Contractor', cost: 'Cost / level', area: 'Work area', ownerFull: 'Project owner', contractorFull: 'Contractor', startDate: 'Start date', expectedFinish: 'Target finish', expectedOpen: 'Target opening', source: 'Source', missing: 'Pending official data', openSource: 'Open source ↗', openMap: 'View on OpenStreetMap ↗', sourceFit: 'Best for: ', sourceCta: 'Open source portal', metricCostValue: 'Multi-level', mapReady: 'Interactive construction map is ready. Drag, zoom, switch base maps, and tap project hotspots.', initHint: 'Drag or use the zoom buttons, then tap a project hotspot for owner, contractor, timeline, and source. Switch base maps when you need official street maps, aerial imagery, or cadastre reference.', resetHint: 'Back to the full Taiwan view. Tap any project hotspot to start exploring.', filterEmpty: 'No matching projects right now. Try another place, contractor, or source keyword.', mapTouchEnable: 'Move map', mapTouchDisable: 'Lock map', mapTouchActive: 'Map dragging is on. Tap again to prioritize page scrolling.', mapTouchLocked: 'Mobile scrolling now comes first, so the map will not trap the page. Tap “Move map” to drag it.', languageButton: '中', ariaLanguage: 'Switch to Chinese', zoomControl: 'Map zoom', zoomIn: 'Zoom in', zoomOut: 'Zoom out'
  }
};

const TYPE_LABELS = { public: 'Public works', transit: 'Transit / transport', road: 'Road / utilities', planning: 'Planning / EIA', building: 'Buildings / campuses', energy: 'Water / energy / ports' };
const STATUS_LABELS = { '施工中': 'Under construction', '規劃/招標準備': 'Planning / tender prep', '規劃/審查資料源': 'Planning / review source', '規劃/預算資料源': 'Planning / budget source', '規劃/施工並行': 'Planning and staged construction', '規劃/環評資料源': 'Planning / EIA source', '即時資料源': 'Live data source', '資料源': 'Data source' };

const refs = { search: document.querySelector('#searchInput'), typeFilter: document.querySelector('#typeFilter'), statusFilter: document.querySelector('#statusFilter'), projectList: document.querySelector('#projectList'), resetMap: document.querySelector('#resetMap'), toggleSources: document.querySelector('#toggleSources'), metricProjects: document.querySelector('#metricProjects'), metricCost: document.querySelector('#metricCost'), metricSources: document.querySelector('#metricSources'), sourceCards: document.querySelector('#sourceCards'), map: document.querySelector('#map'), mapStatus: document.querySelector('#mapStatus'), languageToggle: document.querySelector('#languageToggle') };
let activeId = '', visibleProjects = [...PROJECTS], mapView = { ...DEFAULT_VIEW }, dragStart = null, resizeTimer = null, mobileMapActive = false, currentLang = localStorage.getItem(LANG_KEY) === 'en' ? 'en' : 'zh';

init();

function init() { hydrateFilters(); renderMetrics(); setLanguage(currentLang, { skipRender: true }); renderSources(); renderProjects(visibleProjects); renderMap(visibleProjects); bindEvents(); showMapHint(t('initHint')); }
function bindEvents() { refs.search.addEventListener('input', applyFilters); refs.typeFilter.addEventListener('change', applyFilters); refs.statusFilter.addEventListener('change', applyFilters); refs.resetMap.addEventListener('click', resetView); refs.toggleSources.addEventListener('click', () => document.querySelector('#sourcePanel').scrollIntoView({ behavior: 'smooth', block: 'start' })); refs.languageToggle.addEventListener('click', () => setLanguage(currentLang === 'zh' ? 'en' : 'zh')); refs.map.addEventListener('wheel', e => { e.preventDefault(); setZoom(mapView.zoom + (e.deltaY < 0 ? 1 : -1)); }, { passive: false }); refs.map.addEventListener('pointerdown', e => { if (e.target.closest('[data-project-id]') || e.target.closest('.map-zoom-control') || e.target.closest('.map-touch-toggle') || e.target.closest('.base-layer-control') || isTouchScrollFirst(e)) return; refs.map.setPointerCapture?.(e.pointerId); dragStart = { x: e.clientX, y: e.clientY, centerWorld: latLngToWorld(mapView.lat, mapView.lng, mapView.zoom) }; refs.map.classList.add('dragging'); }); refs.map.addEventListener('pointermove', e => { if (!dragStart) return; const next = worldToLatLng(dragStart.centerWorld.x - (e.clientX - dragStart.x), dragStart.centerWorld.y - (e.clientY - dragStart.y), mapView.zoom); mapView = { ...mapView, lat: next.lat, lng: next.lng }; renderMap(visibleProjects, { keepStatus: true }); }); refs.map.addEventListener('pointerup', endDrag); refs.map.addEventListener('pointercancel', endDrag); window.addEventListener('resize', () => { clearTimeout(resizeTimer); resizeTimer = setTimeout(() => renderMap(visibleProjects, { keepStatus: true }), 120); }); }
function setLanguage(lang, options = {}) { currentLang = lang; localStorage.setItem(LANG_KEY, lang); document.documentElement.lang = lang === 'zh' ? 'zh-Hant' : 'en'; document.title = t('documentTitle'); document.querySelectorAll('[data-i18n]').forEach(el => { const key = el.dataset.i18n; if (typeof COPY[lang][key] === 'string') el.textContent = COPY[lang][key]; }); refs.search.placeholder = t('searchPlaceholder'); refs.languageToggle.textContent = t('languageButton'); refs.languageToggle.setAttribute('aria-label', t('ariaLanguage')); hydrateFilters(); renderMetrics(); if (!options.skipRender) { applyFilters(); renderSources(); showMapHint(t('initHint')); } }
function hydrateFilters() { const oldType = refs.typeFilter.value || 'all', oldStatus = refs.statusFilter.value || 'all'; refs.typeFilter.innerHTML = `<option value="all">${escapeHtml(t('typeAll'))}</option>`; Object.entries(PROJECT_TYPES).forEach(([key, cfg]) => refs.typeFilter.add(new Option(typeLabel(key, cfg), key))); refs.statusFilter.innerHTML = `<option value="all">${escapeHtml(t('statusAll'))}</option>`; [...new Set(PROJECTS.map(p => p.status))].sort((a,b)=>a.localeCompare(b,'zh-Hant')).forEach(s => refs.statusFilter.add(new Option(statusLabel(s), s))); refs.typeFilter.value = oldType; refs.statusFilter.value = oldStatus; }
function applyFilters() { const keyword = normalize(refs.search.value), type = refs.typeFilter.value, status = refs.statusFilter.value; visibleProjects = PROJECTS.filter(p => { const text = normalize(`${p.name} ${p.shortName} ${p.region} ${p.owner} ${p.contractor} ${p.summary} ${p.area} ${p.sourceLabel} ${p.tags?.join(' ')}`); return (type === 'all' || p.type === type) && (status === 'all' || p.status === status) && (!keyword || text.includes(keyword)); }); if (!visibleProjects.some(p => p.id === activeId)) activeId = ''; renderProjects(visibleProjects); renderMap(visibleProjects); showMapHint(visibleProjects.length ? (currentLang === 'en' ? `Showing ${visibleProjects.length} project hotspots and data layers.` : `目前顯示 ${visibleProjects.length} 個工程熱點與資料圖層。`) : t('filterEmpty')); }
function resetView() { activeId = ''; visibleProjects = [...PROJECTS]; refs.search.value = ''; refs.typeFilter.value = 'all'; refs.statusFilter.value = 'all'; mapView = { ...DEFAULT_VIEW }; renderProjects(visibleProjects); renderMap(visibleProjects); showMapHint(t('resetHint')); }
function renderProjects(projects) { refs.projectList.innerHTML = ''; if (!projects.length) { refs.projectList.innerHTML = `<div class="project-card empty"><h3>${escapeHtml(t('emptyTitle'))}</h3><p>${escapeHtml(t('emptyText'))}</p></div>`; return; } const f = document.createDocumentFragment(); projects.forEach(raw => { const card = document.createElement('article'); card.className = `project-card${raw.id === activeId ? ' active' : ''}`; card.tabIndex = 0; card.dataset.projectId = raw.id; card.innerHTML = `<div class="meta-row"><span class="badge">${escapeHtml(typeLabel(raw.type))}</span><span class="badge status">${escapeHtml(statusLabel(raw.status))}</span><span class="badge confidence">${escapeHtml(raw.confidence || t('missing'))}</span></div><h3>${escapeHtml(raw.name)}</h3><p>${escapeHtml(raw.region)}｜${escapeHtml(raw.summary || raw.area || '')}</p><div class="mini-facts"><span>${escapeHtml(t('owner'))}：${escapeHtml(shorten(raw.owner,18))}</span><span>${escapeHtml(t('contractor'))}：${escapeHtml(shorten(raw.contractor,18))}</span></div>`; card.addEventListener('click', () => selectProject(raw.id)); card.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); selectProject(raw.id); } }); f.append(card); }); refs.projectList.append(f); }
function renderMap(projects, options = {}) { refs.map.classList.toggle('map-touch-active', mobileMapActive); const width = Math.max(refs.map.clientWidth || 900, 320), height = Math.max(refs.map.clientHeight || 360, 260); refs.map.innerHTML = `<div class="real-map" style="width:${width}px;height:${height}px" aria-label="${escapeAttr(currentLang === 'en' ? 'Taiwan construction map with switchable base maps' : '可切換底圖的台灣工程互動地圖')}"><div class="tile-layer">${buildTiles(width,height)}</div><svg class="map-overlay" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" aria-hidden="false">${buildOverlay(projects,width,height)}</svg><button type="button" class="map-touch-toggle">${escapeHtml(mobileMapActive ? t('mapTouchDisable') : t('mapTouchEnable'))}</button><div class="map-zoom-control" aria-label="${escapeAttr(t('zoomControl'))}"><button type="button" data-zoom="in" aria-label="${escapeAttr(t('zoomIn'))}">＋</button><button type="button" data-zoom="out" aria-label="${escapeAttr(t('zoomOut'))}">－</button></div><div class="map-attribution">© OpenStreetMap contributors</div></div>`; refs.map.querySelector('.map-touch-toggle')?.addEventListener('click', () => { mobileMapActive = !mobileMapActive; renderMap(visibleProjects, { keepStatus: true }); showMapHint(mobileMapActive ? t('mapTouchActive') : t('mapTouchLocked')); }); refs.map.querySelectorAll('[data-project-id]').forEach(el => el.addEventListener('click', e => { e.stopPropagation(); selectProject(el.dataset.projectId); })); refs.map.querySelector('[data-zoom="in"]')?.addEventListener('click', () => setZoom(mapView.zoom + 1)); refs.map.querySelector('[data-zoom="out"]')?.addEventListener('click', () => setZoom(mapView.zoom - 1)); if (!options.keepStatus) showMapHint(t('mapReady')); }
function buildTiles(w,h) { const c = latLngToWorld(mapView.lat,mapView.lng,mapView.zoom), sx = Math.floor((c.x-w/2)/TILE_SIZE), ex = Math.floor((c.x+w/2)/TILE_SIZE), sy = Math.floor((c.y-h/2)/TILE_SIZE), ey = Math.floor((c.y+h/2)/TILE_SIZE), max = 2 ** mapView.zoom, out = []; for (let x=sx; x<=ex; x++) for (let y=sy; y<=ey; y++) { if (y<0 || y>=max) continue; const wx = ((x % max) + max) % max; out.push(`<img class="map-tile" src="https://tile.openstreetmap.org/${mapView.zoom}/${wx}/${y}.png" alt="" loading="lazy" decoding="async" style="left:${x*TILE_SIZE-c.x+w/2}px;top:${y*TILE_SIZE-c.y+h/2}px" onerror="this.classList.add('tile-error')" />`); } return out.join(''); }
function buildOverlay(projects,w,h) { return `<g class="project-layer">${projects.map(p => createProjectGraphic(p,w,h)).join('')}</g>`; }
function createProjectGraphic(raw,w,h) { const color = PROJECT_TYPES[raw.type]?.color || '#2f80ed', centroid = getCentroid(raw.geometry.coordinates), labelPoint = mapPixel(centroid,w,h), active = raw.id === activeId ? ' active' : '', label = `<text x="${labelPoint.x+15}" y="${labelPoint.y-13}">${escapeHtml(raw.shortName || raw.name)}</text>`, title = `${raw.shortName || raw.name}｜${statusLabel(raw.status)}`; if (raw.geometry.type === 'line') { const points = raw.geometry.coordinates.map(c => { const pt = mapPixel(c,w,h); return `${pt.x},${pt.y}`; }).join(' '); return `<g class="project-item project-line${active}" tabindex="0" data-project-id="${escapeAttr(raw.id)}" style="--project-color:${escapeAttr(color)}"><title>${escapeHtml(title)}</title><polyline points="${points}"></polyline><circle cx="${labelPoint.x}" cy="${labelPoint.y}" r="11"></circle>${label}</g>`; } if (raw.geometry.type === 'polygon') { const points = raw.geometry.coordinates.map(c => { const pt = mapPixel(c,w,h); return `${pt.x},${pt.y}`; }).join(' '); return `<g class="project-item project-polygon${active}" tabindex="0" data-project-id="${escapeAttr(raw.id)}" style="--project-color:${escapeAttr(color)}"><title>${escapeHtml(title)}</title><polygon points="${points}"></polygon><circle cx="${labelPoint.x}" cy="${labelPoint.y}" r="11"></circle>${label}</g>`; } return `<g class="project-item project-point${active}" tabindex="0" data-project-id="${escapeAttr(raw.id)}" style="--project-color:${escapeAttr(color)}"><title>${escapeHtml(title)}</title><circle cx="${labelPoint.x}" cy="${labelPoint.y}" r="16"></circle>${label}</g>`; }
function selectProject(id) { const raw = PROJECTS.find(p => p.id === id); if (!raw) return; activeId = id; const center = getCentroid(raw.geometry.coordinates); if (raw.geometry.type !== 'polygon') mapView = { ...mapView, lat: center[0], lng: center[1], zoom: Math.max(mapView.zoom, 11) }; renderProjects(visibleProjects); renderMap(visibleProjects, { keepStatus: true }); showProjectDetail(raw); refs.projectList.querySelector(`[data-project-id="${cssEscape(id)}"]`)?.scrollIntoView({ block: 'nearest', behavior: 'smooth' }); }
function showProjectDetail(raw) { refs.mapStatus.innerHTML = `<article class="map-detail-card"><div class="meta-row"><span class="badge">${escapeHtml(typeLabel(raw.type))}</span><span class="badge status">${escapeHtml(statusLabel(raw.status))}</span><span class="badge confidence">${escapeHtml(raw.confidence || t('missing'))}</span></div><h3>${escapeHtml(raw.name)}</h3><p>${escapeHtml(raw.summary || raw.area || '')}</p><dl>${detailRow(t('cost'),raw.cost)}${detailRow(t('area'),`${raw.region}｜${raw.area}`)}${detailRow(t('ownerFull'),raw.owner)}${detailRow(t('contractorFull'),raw.contractor)}${detailRow(t('startDate'),raw.startDate)}${detailRow(t('expectedFinish'),raw.expectedFinish)}${detailRow(t('expectedOpen'),raw.expectedOpen)}${detailRow(t('source'),raw.sourceLabel)}</dl><div class="detail-actions"><a href="${safeUrl(raw.source)}" target="_blank" rel="noopener noreferrer">${escapeHtml(t('openSource'))}</a><a href="${safeUrl(openMapUrl(raw))}" target="_blank" rel="noopener noreferrer">${escapeHtml(t('openMap'))}</a></div></article>`; }
function renderSources() { if (!refs.sourceCards || refs.sourceCards.classList.contains('home-source-grid')) return; refs.sourceCards.innerHTML = DATA_SOURCES.map(s => `<article class="source-card"><div class="source-topline"><span class="badge">${escapeHtml(s.category)}</span><span>${escapeHtml(s.kind)}</span></div><h3>${escapeHtml(s.name)}</h3><p><strong>${escapeHtml(t('sourceFit'))}</strong>${escapeHtml(s.fitFor)}</p><p>${escapeHtml(s.note)}</p><a href="${safeUrl(s.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(t('sourceCta'))}</a></article>`).join(''); }
function renderMetrics(){ refs.metricProjects.textContent=PROJECTS.length.toString(); refs.metricSources.textContent=DATA_SOURCES.length.toString(); refs.metricCost.textContent=t('metricCostValue'); }
function showMapHint(m){ refs.mapStatus.hidden=false; refs.mapStatus.textContent=m; }
function detailRow(l,v){ return `<div><dt>${escapeHtml(l)}</dt><dd>${escapeHtml(v || t('missing'))}</dd></div>`; }
function setZoom(z){ z=clamp(Math.round(z),MIN_ZOOM,MAX_ZOOM); if(z===mapView.zoom)return; mapView={...mapView,zoom:z}; renderMap(visibleProjects,{keepStatus:true}); showMapHint(currentLang === 'en' ? `Current map zoom: ${z}.` : `目前地圖縮放層級：${z}。`); }
function mapPixel(c,w,h){ const p=latLngToWorld(c[0],c[1],mapView.zoom), center=latLngToWorld(mapView.lat,mapView.lng,mapView.zoom); return {x:Math.round(p.x-center.x+w/2),y:Math.round(p.y-center.y+h/2)}; }
function latLngToWorld(lat,lng,zoom){ const sin=Math.sin((clamp(lat,-85.05112878,85.05112878)*Math.PI)/180), scale=TILE_SIZE*2**zoom; return {x:((lng+180)/360)*scale,y:(0.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*scale}; }
function worldToLatLng(x,y,zoom){ const scale=TILE_SIZE*2**zoom, lng=(x/scale)*360-180, n=Math.PI-(2*Math.PI*y)/scale, lat=(180/Math.PI)*Math.atan(0.5*(Math.exp(n)-Math.exp(-n))); return {lat:clamp(lat,-85.05112878,85.05112878),lng:wrapLng(lng)}; }
function getCentroid(coords){ const pts=flattenCoordinates(coords); if(!pts.length)return[DEFAULT_VIEW.lat,DEFAULT_VIEW.lng]; const sum=pts.reduce((a,p)=>[a[0]+p[0],a[1]+p[1]],[0,0]); return [sum[0]/pts.length,sum[1]/pts.length]; }
function flattenCoordinates(v){ if(!Array.isArray(v))return[]; if(typeof v[0]==='number'&&typeof v[1]==='number')return[v]; return v.flatMap(flattenCoordinates); }
function openMapUrl(p){ const [lat,lng]=getCentroid(p.geometry.coordinates); return p.openMapUrl || `https://www.openstreetmap.org/?mlat=${lat.toFixed(5)}&mlon=${lng.toFixed(5)}#map=14/${lat.toFixed(5)}/${lng.toFixed(5)}`; }
function isTouchScrollFirst(e){ return e.pointerType!=='mouse'&&window.matchMedia('(max-width: 760px), (pointer: coarse)').matches&&!mobileMapActive; }
function typeLabel(type,cfg=PROJECT_TYPES[type]){ return currentLang==='en' ? (TYPE_LABELS[type]||'Project') : (cfg?.label||'工程'); }
function statusLabel(s){ return currentLang==='en' ? (STATUS_LABELS[s]||'Project status pending') : s; }
function endDrag(e){ if(!dragStart)return; refs.map.releasePointerCapture?.(e.pointerId); dragStart=null; refs.map.classList.remove('dragging'); }
function t(k){ return COPY[currentLang][k] ?? COPY.zh[k] ?? k; }
function normalize(v){ return String(v||'').trim().toLowerCase(); }
function clamp(v,min,max){ return Math.max(min,Math.min(max,v)); }
function wrapLng(lng){ return ((((lng+180)%360)+360)%360)-180; }
function shorten(v,max){ const text=String(v||t('missing')); return text.length>max?`${text.slice(0,max)}…`:text; }
function safeUrl(v){ const text=String(v||''); return text.startsWith('https://')||text.startsWith('http://') ? escapeAttr(text) : '#'; }
function cssEscape(v){ return String(v).replaceAll('\\','\\\\').replaceAll('"','\\"'); }
function escapeHtml(v){ return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); }
function escapeAttr(v){ return escapeHtml(v).replaceAll('`','&#096;'); }
