const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];

const DATA = "/data/active_construction_projects.geojson?v=20260630-main-layers-5";
const CK = "tcmap.active.layers.v10";
const LK = "tcmap.lang";
const TS = 256;
const HOME = [120.96, 23.72];

const CITY = {
  臺北: [[121.5654, 25.033], "Taipei"], 新北: [[121.4657, 25.012], "New Taipei"], 桃園: [[121.301, 24.993], "Taoyuan"], 臺中: [[120.6736, 24.1477], "Taichung"], 臺南: [[120.227, 22.999], "Tainan"], 高雄: [[120.301, 22.627], "Kaohsiung"], 基隆: [[121.739, 25.128], "Keelung"], 新竹: [[120.968, 24.803], "Hsinchu"], 苗栗: [[120.821, 24.564], "Miaoli"], 彰化: [[120.516, 24.075], "Changhua"], 南投: [[120.987, 23.838], "Nantou"], 雲林: [[120.431, 23.709], "Yunlin"], 嘉義: [[120.441, 23.486], "Chiayi"], 屏東: [[120.488, 22.669], "Pingtung"], 宜蘭: [[121.753, 24.759], "Yilan"], 花蓮: [[121.606, 23.987], "Hualien"], 臺東: [[121.144, 22.755], "Taitung"], 澎湖: [[119.566, 23.569], "Penghu"], 金門: [[118.318, 24.436], "Kinmen"], 連江: [[119.95, 26.16], "Lienchiang"]
};

const CAT = [
  ["public-works", "公共工程", "Public Works", "#35d4ff", "公部門建設、水利、港灣、社宅與市政工程。", "Civic works, water, ports, public housing, and municipal infrastructure."],
  ["roads-utilities", "道路/管線", "Roads & Utilities", "#ffb84d", "道路、橋梁、公路、排水、污水與地下管線工程。", "Roads, bridges, highways, drainage, sewage, and underground utilities."],
  ["transit", "捷運/交通", "Metro & Transport", "#9b7cff", "捷運、鐵路、車站、路廊與交通節點工程。", "Metro, rail, stations, corridors, and mobility-node projects."],
  ["buildings-parks", "建築/園區", "Buildings & Parks", "#30d68a", "航廈、社宅、公有建築、科學園區、產業園區與航空城。", "Terminals, public housing, public buildings, science parks, industrial parks, and aerotropolis zones."],
  ["planning-eia", "規劃/環評", "Planning & Environmental Review", "#ffcf66", "計畫中、評估中、設計中、環評與前期公開資料。", "Planned, under-evaluation, in-design, environmental-review, and early public records."]
];
const CB = Object.fromEntries(CAT.map(x => [x[0], x]));
const ST = ["計畫中", "計劃中", "評估中", "設計中", "施工中", "完工"];
const STE = { 計畫中: "Planned", 計劃中: "Planned", 評估中: "Under Evaluation", 設計中: "In Design", 施工中: "Under Construction", 完工: "Completed within 1 month" };
const MENU = [["home", "全國工程概況", "National Overview", "./index.html"], ...CAT.map(c => ["sector", c[1], c[2], `./category.html?sector=${encodeURIComponent(c[0])}`]), ["sources", "資料入口", "Data Sources", "./sources.html"]];

const T = {
  zh: { brand: "台灣工程地圖", line: "全國工程概況 × 五大圖層 × 資料入口", overview: "全國工程概況", osm: "OpenStreetMap 電子地圖", cats: "工程圖層", src: "資料入口", pill: "一進首頁，先看全國工程熱度。", h1: "全國工程概況，縣市量體一張圖開看。", lead: "給工程公司、發包甲方、地理地圖愛好者與年輕人看的工程雷達。先看各縣市工程總數，再依公共工程、道路/管線、捷運/交通、建築/園區、規劃/環評五大圖層切換。", open: "打開全國工程概況", openSector: "打開分類地圖", projects: "現況工程", counties: "有資料縣市", lanes: "主要圖層", sectorSingle: "目前圖層", sourcePortals: "公開來源", catTitle: "五大工程圖層，對齊首頁現況資料。", catText: "每個圖層都能用縣市查詢，也能看點位、甲方、乙方、金額、期程與來源。查案不用繞路，直接切到你要的工程線。", countyTitle: "各縣市工程總數與分類盤點", countyText: "點地圖縣市標記或下方卡片，查看該縣市總數與各工程分類；分類數字可直接串到對應分類頁。", search: "搜尋", cityFilter: "縣市", status: "辦理狀態", reset: "回到全台總覽", resetSector: "回到分類全覽", boot: "工程清單已可用，地圖背景載入中。", ready: "OpenStreetMap 已載入，工程點位與縣市統計可查。", slow: "地圖底圖暫時讀取較慢，先保留可查詢的台灣簡圖與工程清單。", retry: "重試底圖", dataSlow: "工程資料讀取較慢，請先用分類與縣市入口查詢。", list: "工程清單", listTitle: "點位、甲方、乙方、期程與來源。", footer: "資料以公開入口可回查內容整理；正式引用請回主管機關、發包單位與公告來源確認最新版本。地圖底圖 © OpenStreetMap contributors。", allCity: "全部縣市", allStatus: "全部狀態", empty: "目前沒有符合條件的工程", source: "來源", owner: "甲方", contractor: "乙方", budget: "金額", period: "期程", address: "位置", verified: "待補資料 / To be verified", prev: "上一頁", next: "下一頁", page: "頁", cityTotal: "工程總數", sideTitle: "分縣市看工程點位", sideText: "選擇縣市或搜尋工程名稱、甲方、乙方，地圖會同步聚焦。", basic: "基本資料", range: "位置範圍", content: "工程內容", party: "發包與廠商", cost: "金額成本", schedule: "時間期程", progress: "施工進度", rules: "審查法規", publicInfo: "民眾資訊", updated: "更新日期", geometry: "地圖範圍格式", scope: "工程內容", start: "開工／啟動", plannedEnd: "預定完成", review: "審查重點", publicNotice: "民眾資訊", activeFilter: "現況檢核", activeKept: "符合首頁現況規則", activeMoved: "已超過首頁現況範圍" },
  en: { brand: "Taiwan Construction Map", line: "National overview × five layers × source portals", overview: "National Overview", osm: "OpenStreetMap", cats: "Project Layers", src: "Data Sources", pill: "Start with Taiwan’s infrastructure pulse.", h1: "A national project overview, mapped by city.", lead: "A clear project radar for engineering firms, project owners, geo-map fans, and the next-gen infrastructure crowd. Start with city totals, then switch across five active layers: public works, roads/utilities, metro/transport, buildings/parks, and planning/environmental review.", open: "Open national overview", openSector: "Open layer map", projects: "Active projects", counties: "Cities covered", lanes: "Main layers", sectorSingle: "Current layer", sourcePortals: "Source portals", catTitle: "Five project layers aligned with active homepage data.", catText: "Each layer supports city filtering and shows location, owner, contractor, budget, schedule, and source. Fast checks, clean lanes, no maze.", countyTitle: "City totals and sector mix", countyText: "Tap a city marker or card to see total projects and sector counts. Each count links straight to its city-filtered layer page.", search: "Search", cityFilter: "City", status: "Status", reset: "Back to Taiwan overview", resetSector: "Back to layer overview", boot: "Project list is ready while the map background loads.", ready: "OpenStreetMap is ready. Project pins and city stats are live.", slow: "Map tiles are taking longer, so the searchable Taiwan fallback and project list stay available.", retry: "Retry basemap", dataSlow: "Project data is taking longer. Use layer and city entry points first.", list: "Project List", listTitle: "Location, owner, contractor, schedule, and source.", footer: "Compiled from public, traceable sources. For formal use, verify the latest version with the owner agency and source notice. Basemap © OpenStreetMap contributors.", allCity: "All cities", allStatus: "All statuses", empty: "No matching projects yet", source: "Source", owner: "Owner", contractor: "Contractor", budget: "Budget", period: "Schedule", address: "Location", verified: "To be verified", prev: "Previous", next: "Next", page: "Page", cityTotal: "Total projects", sideTitle: "Check projects by city", sideText: "Pick a city or search by project, owner, or contractor. The map follows your query.", basic: "Basics", range: "Location Range", content: "Scope", party: "Owner & Contractor", cost: "Budget", schedule: "Schedule", progress: "Progress", rules: "Review & Rules", publicInfo: "Public Info", updated: "Updated", geometry: "Map geometry", scope: "Scope", start: "Start", plannedEnd: "Planned end", review: "Review note", publicNotice: "Public notice", activeFilter: "Active check", activeKept: "Kept in active homepage view", activeMoved: "Outside active homepage rule" }
};

let lang = localStorage.getItem(LK) || "zh";
let mode = document.body?.dataset.page || "overview";
let sector = new URLSearchParams(location.search).get("sector") || "public-works";
let timeout = false, dataSettled = false, resizeTimer = null;
let S = { all: [], list: [], q: "", city: new URLSearchParams(location.search).get("city") || "", status: "", page: 1, zoom: 7, center: HOME, sel: null, layers: new Set(CAT.map(c => c[0])) };

const tt = k => (T[lang] || T.zh)[k] || T.zh[k] || k;
const esc = v => String(v ?? "").replace(/[&<>\"']/g, m => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[m]));
const cl = k => lang === "en" ? (CB[k]?.[2] || k) : (CB[k]?.[1] || k);
const cc = c => lang === "en" ? (CITY[c]?.[1] || c) : c;
const sl = s => lang === "en" ? (STE[s] || s) : s;

function nav(){ const n = $("#mainNav"); if(!n) return; n.innerHTML = MENU.map(m => `<a href="${m[3]}" ${((mode === "overview" && m[0] === "home") || (mode === "category" && m[0] === "sector" && m[3].includes(encodeURIComponent(sector))) || (mode === "sources" && m[0] === "sources")) ? 'aria-current="page"' : ""}>${esc(lang === "en" ? m[2] : m[1])}</a>`).join(""); }
function tr(){ document.documentElement.lang = lang === "en" ? "en" : "zh-Hant"; $$('[data-t]').forEach(e => e.textContent = tt(e.dataset.t)); const b = $("#lang"); if(b) b.textContent = lang === "en" ? "中" : "EN"; const q = $("#q"); if(q) q.placeholder = lang === "en" ? "Try Taipei, roads, metro, science park" : "例：臺北、道路、捷運、科學園區"; nav(); hero(); renderLayers(); if(timeout) health(tt("slow"), true); apply(false); }
function hero(){ if(mode !== "category") return; sector = CB[sector] ? sector : "public-works"; const c = CB[sector], name = cl(sector); document.title = `${name}｜${lang === "en" ? "Taiwan Construction Map" : "台灣工程地圖"}`; const set = (id, value) => { const el = $(id); if(el) el.textContent = value; }; set("#sectorPill", `${name}｜${lang === "en" ? c[5] : c[4]}`); set("#sectorTitle", lang === "en" ? `${name} Map` : `${name}工程地圖`); set("#sectorLead", lang === "en" ? `Focused on ${name} projects, with city filtering for location, owner, contractor, budget, schedule, and source. Built for quick mobile field checks.` : `聚焦${name}工程，可分縣市查詢工程點位、甲方、乙方、金額、期程與來源。手機上也能快速看案場分布。`); set("#sectorEyebrow", name); set("#sectorMapTitle", lang === "en" ? `${name} Map` : `${name}工程地圖`); set("#sectorSideTitle", tt("sideTitle")); set("#sectorSideText", tt("sideText")); }
function renderLayers(){ const box = $("#layerToggles div"); if(!box) return; box.innerHTML = CAT.map(c => `<label><input type="checkbox" value="${c[0]}" ${S.layers.has(c[0]) ? "checked" : ""}><span>${esc(lang === "en" ? c[2] : c[1])}</span></label>`).join(""); $$('#layerToggles input').forEach(i => i.onchange = () => { i.checked ? S.layers.add(i.value) : S.layers.delete(i.value); S.page = 1; apply(); }); }
function cityOf(p){ const t = [p.city, p.address, p.name].join(" "); return Object.keys(CITY).find(c => t.includes(c)) || "其他"; }
function cat(p){ const x = [p.category, p.name].join(" "); if(/道路|橋|公路|路面|挖掘|沿河|管線|污水|排水/.test(x)) return "roads-utilities"; if(/捷運|鐵路|高鐵|台鐵|車站|交通/.test(x)) return "transit"; if(/園區|航空城|科學城|建築|社宅|航廈|場館|住宅/.test(x)) return "buildings-parks"; if(/環評|規劃|計畫|可行性|評估|設計/.test(x)) return "planning-eia"; return "public-works"; }
function coord(f,p){ const g = f.geometry || {}; if(g.type === "Point") return g.coordinates; if(g.coordinates){ let x = g.coordinates; while(Array.isArray(x?.[0]?.[0])) x = x[0]; return Array.isArray(x?.[0]) ? x[0] : x; } return CITY[cityOf(p)]?.[0] || HOME; }
function dval(v){ if(!v) return null; const d = new Date(`${String(v).slice(0,10)}T00:00:00+08:00`); return Number.isNaN(d.getTime()) ? null : d; }
function activeOK(p){ if(["計畫中", "計劃中", "評估中", "設計中", "施工中"].includes(p.status)) return true; if(p.status !== "完工") return false; const d = dval(p.completed_at || p.opened_at || p.planned_end_date || p.end_date); return !!d && Date.now() - d.getTime() <= 31 * 864e5; }
function norm(f,i){ const p = f.properties || {}, k = cat(p); return { ...p, id: p.id || `p-${i}`, status: p.status || "待確認", city: cityOf(p), key: k, color: CB[k]?.[3] || CB["public-works"][3], coord: coord(f,p), geometry_type: f.geometry?.type || p.geometry_type || "Point" }; }
function layerOK(p){ return mode === "category" || S.layers.has(p.key); }
function use(data){ const seen = new Set(); let dropped = 0; S.all = (data.features || []).map(norm).filter(p => { const k = [p.name, p.owner, p.address, p.source_url].join("|").toLowerCase(); if(seen.has(k)){ dropped++; return false; } seen.add(k); const ok = activeOK(p); if(!ok) dropped++; return ok; }); window.__tcmapDroppedInactive = dropped; dataSettled = true; apply(); }
async function load(){ let had = false; try{ const c = JSON.parse(localStorage.getItem(CK) || "null"); if(c?.features){ had = true; use(c); } }catch{} const soft = setTimeout(() => { if(!dataSettled && !had){ health(tt("dataSlow")); use({features:[]}); } }, 1500); try{ const ctl = new AbortController(), to = setTimeout(() => ctl.abort(), 4200); const r = await fetch(DATA, { signal: ctl.signal, cache: "no-cache" }); clearTimeout(to); if(!r.ok) throw new Error("data"); const j = await r.json(); clearTimeout(soft); localStorage.setItem(CK, JSON.stringify(j)); use(j); }catch{ clearTimeout(soft); if(!had && !dataSettled){ health(tt("dataSlow")); use({features:[]}); } } }
function filt(p){ const q = S.q.trim().toLowerCase(); return layerOK(p) && (mode !== "category" || p.key === sector) && (!S.city || p.city === S.city) && (!S.status || p.status === S.status) && (!q || [p.name,p.name_en,p.address,p.address_en,p.owner,p.owner_en,p.contractor,p.contractor_en,p.source_name,p.city,cc(p.city),cl(p.key),p.status,sl(p.status)].join(" ").toLowerCase().includes(q)); }
function apply(redraw=true){ S.list = S.all.filter(filt); metrics(); filters(); cats(); cities(); cards(); if(redraw) map(); renderLayers(); }
function metrics(){ const a = mode === "category" ? S.all.filter(p => p.key === sector) : S.all.filter(layerOK), c = new Set(a.map(p => p.city).filter(x => x && x !== "其他")), src = new Set(a.map(p => p.source_name).filter(Boolean)); const set = (id, v) => { const el = $(id); if(el) el.textContent = v; }; set("#m1", a.length.toLocaleString()); set("#m2", c.size.toLocaleString()); set("#m3", mode === "category" ? "1" : CAT.length); set("#m4", src.size.toLocaleString()); }
function filters(){ const cs = $("#cityFilter"); if(cs){ const a = mode === "category" ? S.all.filter(p => p.key === sector) : S.all.filter(layerOK), arr = Object.keys(CITY).filter(c => a.some(p => p.city === c)); cs.innerHTML = `<option value="">${esc(tt("allCity"))}</option>` + arr.map(c => `<option value="${esc(c)}" ${S.city === c ? "selected" : ""}>${esc(cc(c))}</option>`).join(""); } const st = $("#status"); if(st) st.innerHTML = `<option value="">${esc(tt("allStatus"))}</option>` + ST.map(s => `<option value="${esc(s)}" ${S.status === s ? "selected" : ""}>${esc(sl(s))}</option>`).join(""); }
function cnt(arr){ const o = Object.fromEntries(CAT.map(c => [c[0], 0])); arr.forEach(p => o[p.key] = (o[p.key] || 0) + 1); return o; }
function link(k, city=""){ const u = `./category.html?sector=${encodeURIComponent(k)}`; return city ? u + `&city=${encodeURIComponent(city)}` : u; }
function cats(){ const b = $("#catCards"); if(!b) return; const n = cnt(S.all); b.innerHTML = CAT.map(c => `<a class="cat" href="${link(c[0])}" style="--c:${c[3]}"><b>${esc(cl(c[0]))}</b><span>${n[c[0]] || 0} ${lang === "en" ? "projects" : "件工程"}</span><em>${esc(lang === "en" ? c[5] : c[4])}</em></a>`).join(""); }
function groups(){ const o = {}; S.list.forEach(p => { if(p.city !== "其他") (o[p.city] ??= []).push(p); }); return Object.entries(o).sort((a,b) => b[1].length - a[1].length); }
function cities(){ const b = $("#cityCards"); if(!b) return; const g = groups(); if(!g.length){ b.innerHTML = `<div class="empty"><b>${esc(tt("empty"))}</b></div>`; return; } b.innerHTML = g.map(([city, arr]) => { const n = cnt(arr), links = CAT.filter(c => n[c[0]]).map(c => `<a href="${link(c[0],city)}" style="--c:${c[3]}">${esc(cl(c[0]))}<b>${n[c[0]]}</b></a>`).join(""); return `<article class="city ${S.city === city ? "on" : ""}"><button type="button" class="cityMain" data-city="${esc(city)}"><b>${esc(cc(city))}</b><span>${esc(tt("cityTotal"))} ${arr.length}</span></button><div class="cityLinks">${links}</div></article>`; }).join(""); $$(".cityMain", b).forEach(x => x.onclick = () => selCity(x.dataset.city)); }
function fmt(v){ if(v == null || v === "" || v === 0) return tt("verified"); if(typeof v === "number") return v >= 1e8 ? `NT$${Math.round(v/1e8).toLocaleString()}億` : `NT$${v.toLocaleString()}`; return String(v); }
function card(p){ const name = lang === "en" && p.name_en ? p.name_en : p.name, addr = lang === "en" && p.address_en ? p.address_en : p.address; return `<article class="proj" style="--c:${p.color}" data-id="${esc(p.id)}"><i>${esc(cl(p.key))}｜${esc(sl(p.status))}</i><h3>${esc(name || tt("verified"))}</h3><p>${esc(addr || tt("verified"))}</p><dl><div><dt>${esc(tt("owner"))}</dt><dd>${esc(fmt(lang === "en" && p.owner_en ? p.owner_en : p.owner))}</dd></div><div><dt>${esc(tt("contractor"))}</dt><dd>${esc(fmt(lang === "en" && p.contractor_en ? p.contractor_en : p.contractor))}</dd></div><div><dt>${esc(tt("budget"))}</dt><dd>${esc(fmt(p.budget_ntd))}</dd></div><div><dt>${esc(tt("period"))}</dt><dd>${esc(fmt(p.start_date))} → ${esc(fmt(p.planned_end_date))}</dd></div></dl>${p.source_url ? `<a href="${esc(p.source_url)}" target="_blank" rel="noopener noreferrer">${esc(tt("source"))}</a>` : ""}</article>`; }
function cards(){ const b = $("#list"); if(!b) return; const pages = Math.max(1, Math.ceil(S.list.length / 12)); S.page = Math.min(Math.max(1, S.page), pages); const arr = S.list.slice((S.page - 1) * 12, S.page * 12); let h = arr.length ? arr.map(card).join("") : `<div class="empty"><b>${esc(tt("empty"))}</b></div>`; if(S.list.length > 12) h += `<div class="pager"><button id="prevPage" ${S.page <= 1 ? "disabled" : ""}>${esc(tt("prev"))}</button><span>${esc(tt("page"))} ${S.page} / ${pages}</span><button id="nextPage" ${S.page >= pages ? "disabled" : ""}>${esc(tt("next"))}</button></div>`; b.innerHTML = h; $$(".proj", b).forEach(e => e.onclick = () => { S.sel = S.all.find(p => p.id === e.dataset.id); if(S.sel){ S.center = S.sel.coord; S.zoom = Math.max(S.zoom, 10); map(); detail(S.sel); } }); const prev = $("#prevPage"), next = $("#nextPage"); if(prev) prev.onclick = () => { S.page--; cards(); }; if(next) next.onclick = () => { S.page++; cards(); }; }
function sec(title, rows){ return `<details class="detailSect"><summary>${esc(title)}</summary><dl>${rows.map(([k,v]) => `<div><dt>${esc(k)}</dt><dd>${esc(fmt(v))}</dd></div>`).join("")}</dl></details>`; }
function detail(p){ const d = $("#detail"); if(!d) return; if(!p){ d.innerHTML = ""; return; } const name = lang === "en" && p.name_en ? p.name_en : p.name, addr = lang === "en" && p.address_en ? p.address_en : p.address, owner = lang === "en" && p.owner_en ? p.owner_en : p.owner, contractor = lang === "en" && p.contractor_en ? p.contractor_en : p.contractor; d.innerHTML = `<article><b>${esc(name || tt("verified"))}</b><p>${esc(cl(p.key))}｜${esc(sl(p.status))}</p><div class="summaryChips"><span>${esc(tt("owner"))}：${esc(fmt(owner))}</span><span>${esc(tt("contractor"))}：${esc(fmt(contractor))}</span><span>${esc(tt("budget"))}：${esc(fmt(p.budget_ntd))}</span><span>${esc(tt("period"))}：${esc(fmt(p.start_date))} → ${esc(fmt(p.planned_end_date))}</span><span>${esc(tt("address"))}：${esc(fmt(addr))}</span></div><div class="detailSections">${sec(tt("basic"), [["ID",p.id],[tt("source"),p.source_name],[tt("updated"),p.updated_at]])}${sec(tt("range"), [[tt("address"),addr],[tt("geometry"),p.geometry_type]])}${sec(tt("content"), [[tt("scope"),p.description || p.scope]])}${sec(tt("party"), [[tt("owner"),owner],[tt("contractor"),contractor]])}${sec(tt("cost"), [[tt("budget"),p.budget_ntd]])}${sec(tt("schedule"), [[tt("start"),p.start_date],[tt("plannedEnd"),p.planned_end_date]])}${sec(tt("progress"), [[tt("status"),sl(p.status)],[tt("progress"),p.progress],[tt("activeFilter"),activeOK(p) ? tt("activeKept") : tt("activeMoved")]])}${sec(tt("rules"), [[tt("review"),p.review_note || p.eia_status]])}${sec(tt("publicInfo"), [[tt("publicNotice"),p.public_notice],[tt("source"),p.source_url]])}</div></article>`; }
function merc([lon,lat],z){ const s = TS * 2 ** z; return [(lon + 180) / 360 * s, (.5 - Math.log((1 + Math.sin(lat * Math.PI/180)) / (1 - Math.sin(lat * Math.PI/180))) / (4 * Math.PI)) * s]; }
function unmerc([x,y],z){ const s = TS * 2 ** z, lon = x / s * 360 - 180, n = Math.PI - 2 * Math.PI * y / s, lat = 180 / Math.PI * Math.atan(.5 * (Math.exp(n) - Math.exp(-n))); return [Math.max(118, Math.min(123.6, lon)), Math.max(21.5, Math.min(26.8, lat))]; }
function tiles(w,h,z,c){ const n = 2 ** z, sx = Math.floor((c[0] - w/2) / TS), ex = Math.floor((c[0] + w/2) / TS), sy = Math.floor((c[1] - h/2) / TS), ey = Math.floor((c[1] + h/2) / TS); let html = '<div class="tiles" aria-hidden="true">'; for(let x = sx; x <= ex; x++) for(let y = sy; y <= ey; y++){ if(y < 0 || y >= n) continue; const wx = ((x % n) + n) % n, l = Math.round(x * TS - c[0] + w/2), t = Math.round(y * TS - c[1] + h/2); html += `<img src="https://tile.openstreetmap.org/${z}/${wx}/${y}.png" loading="eager" decoding="async" referrerpolicy="no-referrer" alt="" style="left:${l}px;top:${t}px">`; } return html + "</div>"; }
function back(w,h){ return `<svg class="local-map" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img" aria-label="Taiwan map background"><defs><linearGradient id="sea" x1="0" x2="1" y1="0" y2="1"><stop offset="0" stop-color="#d9f5ff"/><stop offset="1" stop-color="#f9efe0"/></linearGradient><linearGradient id="land" x1="0" x2="1" y1="0" y2="1"><stop offset="0" stop-color="#ecfff7"/><stop offset="1" stop-color="#d7eefb"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#sea)"/><path d="M ${w*.54} ${h*.10} C ${w*.67} ${h*.15}, ${w*.74} ${h*.31}, ${w*.71} ${h*.45} C ${w*.67} ${h*.62}, ${w*.59} ${h*.78}, ${w*.47} ${h*.92} C ${w*.39} ${h*.78}, ${w*.34} ${h*.63}, ${w*.36} ${h*.45} C ${w*.38} ${h*.27}, ${w*.45} ${h*.16}, ${w*.54} ${h*.10} Z" fill="url(#land)" stroke="#4aa1b9" stroke-width="3"/></svg>`; }
function pinSample(arr, max=120){ if(arr.length <= max) return arr; const buckets = Object.fromEntries(CAT.map(c => [c[0], []])); arr.forEach(p => (buckets[p.key] || buckets["public-works"]).push(p)); const out = [], keys = CAT.map(c => c[0]); while(out.length < max && keys.some(k => buckets[k].length)){ for(const k of keys){ const p = buckets[k].shift(); if(p) out.push(p); if(out.length >= max) break; } } return out; }
function marks(w,h,z,c){ const g = groups().slice(0,24).map(([city,arr]) => { const xy = merc(CITY[city][0], z), l = Math.round(xy[0] - c[0] + w/2), t = Math.round(xy[1] - c[1] + h/2), col = CB[arr[0]?.key || "public-works"][3]; return (l < -90 || l > w + 90 || t < -90 || t > h + 90) ? "" : `<button class="mk citymk" data-city="${esc(city)}" style="left:${l}px;top:${t}px;--c:${col}"><b>${arr.length}</b><span>${esc(cc(city))}</span></button>`; }).join(""); const pins = (S.q || S.city || mode === "category" || S.zoom >= 9) ? pinSample(S.list, 120).map(p => { const xy = merc(p.coord, z), l = Math.round(xy[0] - c[0] + w/2), t = Math.round(xy[1] - c[1] + h/2), nm = lang === "en" && p.name_en ? p.name_en : p.name; return (l < -40 || l > w + 40 || t < -40 || t > h + 40) ? "" : `<button class="mk pmk" data-id="${esc(p.id)}" aria-label="${esc(nm)}" title="${esc(nm)}" style="left:${l}px;top:${t}px;--c:${p.color}"></button>`; }).join("") : ""; return g + pins; }
function health(x,retry=false){ const h = $("#health"); if(!h) return; h.innerHTML = esc(x) + (retry ? ` <button type="button" id="retryMap" style="margin-left:8px;border:0;border-radius:999px;padding:6px 9px;background:#fff;color:#07304b;font-weight:1000">${esc(tt("retry"))}</button>` : ""); const r = $("#retryMap"); if(r) r.onclick = () => { timeout = false; map(); health(tt("boot")); }; }
function watch(m){ const imgs = $$(".tiles img", m); if(!imgs.length) return; let done = 0, failed = false; const finish = () => { done++; if(done >= imgs.length && !failed){ timeout = false; health(tt("ready")); } }; setTimeout(() => { if(done < imgs.length){ timeout = true; health(tt("slow"), true); } }, 3000); imgs.forEach(img => { img.onload = finish; img.onerror = () => { failed = true; timeout = true; health(tt("slow"), true); }; }); }
function map(){ const m = $("#map"); if(!m) return; const w = m.clientWidth || 640, h = m.clientHeight || 460, z = S.zoom, c = merc(S.center, z); m.innerHTML = back(w,h) + tiles(w,h,z,c) + `<div class="marks">${marks(w,h,z,c)}</div><button class="zin" type="button">+</button><button class="zout" type="button">−</button><small>© OpenStreetMap contributors</small>`; watch(m); $(".zin",m).onclick = () => { S.zoom = Math.min(12, S.zoom + 1); map(); }; $(".zout",m).onclick = () => { S.zoom = Math.max(7, S.zoom - 1); map(); }; $$(".citymk",m).forEach(x => x.onclick = () => selCity(x.dataset.city)); $$(".pmk",m).forEach(x => x.onclick = () => { S.sel = S.all.find(p => p.id === x.dataset.id); if(S.sel) detail(S.sel); }); drag(m); }
function drag(m){ let start = null; const down = e => { const p = e.touches ? e.touches[0] : e; start = { x: p.clientX, y: p.clientY, c: merc(S.center,S.zoom) }; }, move = e => { if(!start) return; e.preventDefault(); const p = e.touches ? e.touches[0] : e; S.center = unmerc([start.c[0] - (p.clientX - start.x), start.c[1] - (p.clientY - start.y)], S.zoom); map(); }, up = () => { start = null; }; m.onmousedown = down; m.ontouchstart = down; window.onmousemove = move; window.ontouchmove = move; window.onmouseup = up; window.ontouchend = up; }
function selCity(city){ S.city = S.city === city ? "" : city; S.page = 1; if(S.city && CITY[S.city]){ S.center = CITY[S.city][0]; S.zoom = 9; } else { S.center = HOME; S.zoom = 7; } apply(); }
function events(){ const q = $("#q"); if(q) q.oninput = e => { S.q = e.target.value; S.page = 1; apply(); }; const c = $("#cityFilter"); if(c) c.onchange = e => selCity(e.target.value); const st = $("#status"); if(st) st.onchange = e => { S.status = e.target.value; S.page = 1; apply(); }; const r = $("#reset"); if(r) r.onclick = () => { S.q = ""; S.city = ""; S.status = ""; S.page = 1; S.center = HOME; S.zoom = 7; if(q) q.value = ""; apply(); }; const b = $("#lang"); if(b) b.onclick = () => { lang = lang === "en" ? "zh" : "en"; localStorage.setItem(LK, lang); tr(); }; window.addEventListener("resize", () => { clearTimeout(resizeTimer); resizeTimer = setTimeout(map, 180); }); }

tr();
events();
load();
setTimeout(() => { if(!dataSettled) health(tt("dataSlow")); }, 1600);
map();